const catalogue = [
  {
    id: "00000001",
    type: "milk",
    name: "Alt Co Oat Milk",
    seller: "Alt Co",
    stars: 4.5,
    tag: ["milk", "premium"],
    details: {
      stock: 20,
      price: 159,
      price2: 259,
      weight: "1L",
      packaging: "Closed, Plastic Bottle",
      ingredients:
        "Oat Milk (Water, Oats), Rapeseed Oil, Calcium Carbonate, Calcium Phosphate, Salt, Vitamins (D2, Riboflavin, B12)",
      description:
        "Alt Co Oat Milk is a deliciously creamy alternative to dairy and soy milk. It's perfect for coffee, smoothies, and baking. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Alt Co Oat Milk... for a healthy lifestyle",
      instructions:
        "Shake well before use. Keep refrigerated. Once opened, consume within 7 days. Do not freeze.",
      life: "7 days",
    },
    images: [
      "https://vegandukan.com/cdn/shop/products/minitetrafrontwithoutstrawpng_e1815c24-ea58-41b7-9f00-3c4f70aa6711.png?v=1712060206&width=493",
      "https://vegandukan.com/cdn/shop/files/5_b804b381-dae3-4fa0-bac2-eac4f54a6421.png?v=1714389295&width=493",
      "https://vegandukan.com/cdn/shop/files/22_5053c412-5d2a-4ad4-a0d5-1303a333f51f.png?v=1714389295&width=493",
      "https://vegandukan.com/cdn/shop/files/0_-_01_1.jpg?v=1714389295&width=1100",
      "https://vegandukan.com/cdn/shop/files/0_-_04.jpg?v=1714389295&width=1100",
    ],
    ratings: 100,
    reviews: 13,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000004", "00000002", "00000003"],
    priority: 1,
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000002",
    type: "milk",
    name: "Almond Breeze Milk",
    seller: "Almond Breeze",
    stars: 4.3,
    tag: ["milk", "premium"],
    details: {
      stock: 20,
      price: 259,
      price2: 309,
      weight: "1L",
      packaging: "Closed, Plastic Bottle",
      ingredients:
        "Water, Sugar, Almonds (2%), Calcium Carbonate, Emulsifier (Sunflower Lecithin), Sea Salt, Stabiliser (Gellan Gum), Natural Flavouring, Vitamins (E, D2, B12)",
      description:
        "Almond Breeze is a delicious way to be good to yourself, Provides a source of calcium, Vitamin E, D2, B12, and is low in fat. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Almond Breeze... for a healthy lifestyle",
      instructions:
        "Shake well before use. Keep refrigerated. Once opened, consume within 7 days. Do not freeze.",
      life: "7 days",
    },
    images: [
      "https://vegandukan.com/cdn/shop/files/vdc_august_2023_amy-069.png?v=1712519550&width=493",
      "https://vegandukan.com/cdn/shop/files/vdc_august_2023_amy-078.png?v=1712519559&width=1100",
      "https://vegandukan.com/cdn/shop/files/vdc_august_2023_amy-082.png?v=1712519570&width=1100",
      "https://vegandukan.com/cdn/shop/files/vdc_august_2023_amy-084.png?v=1712519579&width=1100",
    ],
    ratings: 102,
    reviews: 14,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000001", "00000004", "00000003"],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000003",
    type: "milk",
    name: "Almond Breeze Barista Blend",
    seller: "Almond Breeze",
    stars: 4.1,
    tag: ["milk", "premium"],
    details: {
      stock: 20,
      price: 189,
      price2: 259,
      weight: "500mL",
      packaging: "Closed, Plastic Bottle",
      ingredients:
        "Water, Sugar, Almonds (2%), Calcium Carbonate, Emulsifier (Sunflower Lecithin), Sea Salt, Stabiliser (Gellan Gum), Natural Flavouring, Vitamins (E, D2, B12)",
      description:
        "Almond Breeze Barista Blend is a deliciously creamy alternative to dairy and soy milk. It's perfect for coffee, smoothies, and baking. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Almond Breeze... for a healthy lifestyle",
      instructions:
        "Shake well before use. Keep refrigerated. Once opened, consume within 7 days. Do not freeze.",
      life: "7 days",
    },
    images: [
      "https://vegandukan.com/cdn/shop/files/33.png?v=1714388165&width=493",
      "https://vegandukan.com/cdn/shop/files/5_b804b381-dae3-4fa0-bac2-eac4f54a6421.png?v=1714389295&width=493",
      "https://vegandukan.com/cdn/shop/files/22_5053c412-5d2a-4ad4-a0d5-1303a333f51f.png?v=1714389295&width=493",
      "https://vegandukan.com/cdn/shop/files/0_-_01_1.jpg?v=1714389295&width=1100",
      "https://vegandukan.com/cdn/shop/files/0_-_04.jpg?v=1714389295&width=1100",
    ],
    ratings: 170,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000001", "00000002", "00000004"],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000004",
    type: "milk",
    name: "Unsweetened Almond Milk",
    seller: "Super Vegan Sales",
    stars: 4.5,
    tag: ["milk", "premium"],
    details: {
      stock: 20,
      price: 199,
      price2: 249,
      weight: "1L",
      packaging: "Plastic Bottle, Recyclable",
      ingredients:
        "Water, Almonds (2%), Calcium Carbonate, Sea Salt, Emulsifier (Sunflower Lecithin), Stabiliser (Gellan Gum), Natural Flavouring, Vitamins (E, D2, B12)",
      description:
        "Unsweetened Almond Milk is a deliciously creamy alternative to dairy and soy milk. It's perfect for coffee, smoothies, and baking. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Almond Breeze... for a healthy lifestyle",
      instructions:
        "Shake well before use. Keep refrigerated. Once opened, consume within 7 days. Do not freeze.",
      life: "15 days",
    },
    images: [
      "https://vegandukan.com/cdn/shop/products/71fixisxhis._sx679.jpg?v=1712060444&width=493",
      "https://vegandukan.com/cdn/shop/files/Nutrition.jpg?v=1712128995&width=493",
      "https://vegandukan.com/cdn/shop/products/71dwltblljs._sx679.jpg?v=1712128995&width=493",
      "https://vegandukan.com/cdn/shop/products/61p6lxz9mxs._sx679.jpg?v=1712128995&width=493",
      "https://vegandukan.com/cdn/shop/products/615xohxr1ps._sx679.jpg?v=1712128995&width=493",
    ],
    ratings: 70,
    reviews: 5,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000001", "00000002", "00000003"],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000005",
    type: "snacks",
    name: "Bhuja Mix",
    seller: "Bhuja Corner",
    stars: 4.8,
    tag: ["snack"],
    details: {
      stock: 20,
      price: 99,
      price2: 179,
      weight: "200g",
      packaging: "Plastic Packet",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Bhuja Mix is a deliciously spicy and tangy snack mix. It's perfect for tea time, parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Bhuja Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/fRHKhvN2/Designer.jpg",
      "https://i.postimg.cc/7Ldn5YbS/Designer.png",
      "https://i.postimg.cc/9frBXqXW/Designer-1.jpg",
      "https://i.postimg.cc/K8cNVHd3/Designer-2.jpg",
    ],
    ratings: 80,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000006", "00000007", "00000008", "00000009"],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000006",
    type: "snacks",
    name: "Diet Mix",
    seller: "Diet Corner",
    stars: 4.5,
    tag: ["snack"],
    details: {
      stock: 20,
      price: 129,
      price2: 199,
      weight: "200g",
      packaging: "Plastic Packet",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Diet Mix is a deliciously spicy and tangy snack mix. It's perfect for tea time, parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Diet Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/mDYdLs2b/namkeen1-1.jpg",
      "https://i.postimg.cc/RhvgqDNw/namkeen1-2.jpg",
      "https://i.postimg.cc/NFbpXkHS/namkeen1-3.jpg",
      "https://i.postimg.cc/dQ9Wgwx6/namkeen1-4.jpg",
    ],
    ratings: 100,
    reviews: 6,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000005", "00000007", "00000008", "00000009"],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000007",
    type: "snacks",
    name: "Spicy Mix",
    seller: "Vegan's Corner",
    stars: 4.8,
    tag: ["snack"],
    details: {
      stock: 20,
      price: 109,
      price2: 139,
      weight: "200g",
      packaging: "Paper Packet",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Premium delight Mix is a deliciously spicy and tangy snack mix. It's perfect for tea time, parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Diet Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/sX4cF4wx/namkeen2-1.jpg",
      "https://i.postimg.cc/288HDgpD/namkeen2-2.jpg",
    ],
    ratings: 109,
    reviews: 11,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000006", "00000005", "00000008", "00000009"],
    priority: 0,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000008",
    type: "snacks",
    name: "Premium Delight Mix",
    seller: "Vegan's Corner",
    stars: 4.8,
    tag: ["snack"],
    details: {
      stock: 20,
      price: 119,
      price2: 149,
      weight: "200g",
      packaging: "Box Container",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Premium delight Mix is a deliciously spicy and tangy snack mix. It's perfect for tea time, parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Diet Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/NjKpyTfC/snackbox-1.png",
      "https://i.postimg.cc/HsZ6s3H7/snackbox-2.png",
      "https://i.postimg.cc/jjNccbfz/snackbox-3.png",
    ],
    ratings: 100,
    reviews: 12,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000006", "00000007", "00000005", "00000009"],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000009",
    type: "snacks",
    name: "Namkeen Mix",
    seller: "Vegan's Corner",
    stars: 4.8,
    tag: ["snack"],
    details: {
      stock: 20,
      price: 99,
      price2: 129,
      weight: "200g",
      packaging: "Reusable box Container",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Namkeen Mix is a premium and deliciously spicy and tangy snack mix. It's perfect for tea time, parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Diet Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/vZCX5B4Y/snackbox1-1.jpg",
      "https://i.postimg.cc/2yjxCLKw/snackbox-4.png",
      "https://i.postimg.cc/xC2RF4GB/snackbox1-2.jpg",
    ],
    ratings: 100,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000006", "00000007", "00000008", "00000005"],
    priority: 0,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000010",
    type: "instant foods",
    name: "Quick Burger",
    seller: "Vegan's Corner",
    stars: 4.6,
    tag: ["instantfoods", "burger"],
    details: {
      stock: 20,
      price: 99,
      price2: 129,
      weight: "200g",
      packaging: "Plastic Packet",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Instant Burger is a pure vegan and extremely delicious burger. It's perfect for parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Diet Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze. For better taste, use Vegan's Corner's special Mayonnaise and sauce.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/zGDY4x7b/burger-1.jpg",
      "https://i.postimg.cc/ZKxhfG8z/burger-2.jpg",
      "https://i.postimg.cc/W19cV0Y9/burger-3.jpg",
    ],
    ratings: 100,
    reviews: 50,
    rrlink: "https://vegancorner.vercel.app",
    related: [""],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000011",
    type: "quick foods",
    name: "Instant Noodles",
    seller: "Vegan's Corner",
    stars: 4.6,
    tag: ["instantfoods", "noodles"],
    details: {
      stock: 20,
      price: 99,
      price2: 129,
      weight: "200g",
      packaging: "Plastic Packet",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Instant Noodles is a pure vegan and extremely delicious noodles.Specially for kids, It's perfect for parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Diet Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze. Simply drop noodles in hot water, add masala, cook for 5 minutes and enjoy.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/T33Btp2n/noodles-12.jpg",
      "https://i.postimg.cc/DztDf6rc/noodles-13.jpg",
      "https://i.postimg.cc/3J7sDtPS/noodles-2.jpg",
    ],
    ratings: 100,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000012", "00000013"],
    priority: 0,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000012",
    type: "quick foods",
    name: "Instant Noodles",
    seller: "Vegan's Corner",
    stars: 4.3,
    tag: ["instantfoods", "noodles"],
    details: {
      stock: 20,
      price: 179,
      price2: 189,
      weight: "200g",
      packaging: "Plastic Packet",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Instant Noodles is a pure vegan and extremely delicious noodles.Specially for kids, It's perfect for parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Diet Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze. Simply drop noodles in hot water, add masala, cook for 5 minutes and enjoy.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/DfqVZ9Y4/noodles-1.jpg",
      "https://i.postimg.cc/xdkhShzC/noodles-11.jpg",
      "https://i.postimg.cc/R0N5Zqjv/noodles-3.jpg",
      "https://i.postimg.cc/j2YGccCj/noodles-4.jpg",
    ],
    ratings: 120,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000011", "00000013"],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000013",
    type: "quick foods",
    name: "Instant Noodles",
    seller: "Vegan's Corner",
    stars: 4.9,
    tag: ["instantfoods", "noodles"],
    details: {
      stock: 20,
      price: 199,
      price2: 289,
      weight: "200g",
      packaging: "Plastic Packet",
      ingredients:
        "Gram Flour, Vegetable Oil, Peanuts, Lentils, Sago, Rice Flakes, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Instant Noodles is a pure vegan and extremely delicious noodles.Specially for kids, It's perfect for parties, and picnics. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Diet Mix... for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 30 days. Do not freeze. Simply drop noodles in hot water, add masala, cook for 5 minutes and enjoy.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/3J7sDtPS/noodles-2.jpg",
      "https://i.postimg.cc/DztDf6rc/noodles-13.jpg",
      "https://i.postimg.cc/T33Btp2n/noodles-12.jpg",
    ],
    ratings: 90,
    reviews: 12,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000012", "00000011"],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000014",
    type: "milk",
    name: "Mayonnaise Pack",
    seller: "Vegan's Corner",
    stars: 4.8,
    tag: ["milk", "premium", "mayonnaise", "mayo"],
    details: {
      stock: 20,
      price: 299,
      price2: 389,
      weight: "200g",
      packaging: "Container, Recyclable",
      ingredients:
        "Soy Milk, Vinegar, Salt, Sugar, Spices, Turmeric, Citric Acid",
      description:
        "Mayonnaise is a pure vegan and extremely delicious mayonnaise. It's perfect for sandwiches, burgers, and salads. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 60 days. Do not freeze.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/Bvx5DCWp/mayo-1.jpg",
      "https://i.postimg.cc/m2DSqMMZ/mayo-5.jpg",
      "https://i.postimg.cc/k5rFBpHD/mayo-7.jpg",
      "https://i.postimg.cc/NMD1Cfjr/mayo-8.jpg",
    ],
    ratings: 100,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000015"],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000015",
    type: "milk",
    name: "Mayonnaise Premium",
    seller: "Vegan's Corner",
    stars: 4.8,
    tag: ["milk", "premium", "mayonnaise", "mayo"],
    details: {
      stock: 20,
      price: 299,
      price2: 389,
      weight: "200g",
      packaging: "Plastic Packet, Air tight",
      ingredients: "Soy Milk, Vinegar, Salt, Sugar, Spices, Citric Acid",
      description:
        "Mayonnaise is a pure vegan and extremely delicious mayonnaise. It's perfect for sandwiches, burgers, and salads. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a cool, dry place. Once opened, consume within 60 days. Do not freeze. ",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/KjYt6S1p/mayo-2.jpg",
      "https://i.postimg.cc/vHNvdBLr/mayo-3.jpg",
      "https://i.postimg.cc/Nj2kGcpW/mayo-4.jpg",
      "https://i.postimg.cc/63trhGtX/mayo-6.jpg",
    ],
    ratings: 100,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000014"],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000016",
    type: "dairy",
    name: "Butter Multipack",
    seller: "Vegan's Corner",
    stars: 4.8,
    tag: ["dairy", "butter"],
    details: {
      stock: 20,
      price: 199,
      price2: 229,
      weight: "100g",
      packaging: "Plastic Packet",
      ingredients: "Soy Milk, Vinegar, Salt, Sugar, Spices, Citric Acid",
      description:
        "Butter is a pure vegan and extremely delicious butter. It's perfect for sandwiches, burgers. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a fridge, or cool, dry place. Once opened, consume within 5 days. Do not freeze. Simply drop noodles in hot water, add masala, cook for 5 minutes and enjoy.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/x8KSV7BH/butter-10.jpg",
      "https://i.postimg.cc/rwqqMVVp/butter-2.jpg",
      "https://i.postimg.cc/NfqgC8Zm/butter-3.jpg",
      "https://i.postimg.cc/8PRT2JV3/butter-4.jpg",
      "https://i.postimg.cc/JhnmHpBV/butter-6.jpg",
    ],
    ratings: 100,
    reviews: 10,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000017", "00000018"],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000017",
    type: "dairy",
    name: "Butter from Plants",
    seller: "Vegan's Corner",
    stars: 4.4,
    tag: ["dairy", "butter"],
    details: {
      stock: 20,
      price: 99,
      price2: 129,
      weight: "50g",
      packaging: "Plastic Packet",
      ingredients: "Soy Milk, Vinegar, Salt, Sugar, Spices, Citric Acid",
      description:
        "Butter is a pure vegan and extremely delicious butter. It's perfect for sandwiches, burgers. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a fridge, or cool, dry place. Once opened, consume within 5 days. Do not freeze. Simply drop noodles in hot water, add masala, cook for 5 minutes and enjoy.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/MptqGCHm/butter-5.jpg",
      "https://i.postimg.cc/LsbStjzq/butter-7.jpg",
      "https://i.postimg.cc/Y0cwVkDM/butter-9.jpg",
    ],
    ratings: 100,
    reviews: 10,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000016", "00000018"],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000018",
    type: "dairy",
    name: "Butter Premium",
    seller: "Vegan's Corner",
    stars: 4.6,
    tag: ["dairy", "butter"],
    details: {
      stock: 20,
      price: 229,
      price2: 329,
      weight: "50g",
      packaging: "Plastic Packet",
      ingredients: "Soy Milk, Vinegar, Salt, Sugar, Spices, Citric Acid",
      description:
        "Butter is a pure vegan and extremely delicious butter. It's perfect for sandwiches, burgers. It's also free from dairy, eggs, lactose, cholesterol, peanuts, and gluten. It's a great tasting, versatile, and non-dairy alternative for your favourite recipes. Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a fridge, or cool, dry place. Once opened, consume within 5 days. Do not freeze. Simply drop noodles in hot water, add masala, cook for 5 minutes and enjoy.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/Hx8gBj26/butter-8.jpg",
      "https://i.postimg.cc/pVnWBccP/butter-11.jpg",
    ],
    ratings: 100,
    reviews: 10,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000017", "00000016"],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000019",
    type: "grocery",
    name: "Vegan's Meat",
    seller: "Vegan's Corner",
    stars: 4.8,
    tag: ["grocery", "meat"],
    details: {
      stock: 20,
      price: 499,
      price2: 589,
      weight: "250g",
      packaging: "Plastic Packet",
      ingredients:
        "Vegetables, Soy extracts, Vinegar, Salt, Sugar, Spices, Citric Acid",
      description:
        "Veg Meat is a pure vegan and extremely delicious meat. It's perfect for dinner. Switch to Vegan's Corner Special Veg Meat .Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a fridge, or cool, dry place. Once opened, consume within 2 days. Do not freeze.Boil for 10 minutes, then prepare onion, spices and salt according to your taste for 10 minutes, add Vegan's Corner Veg Meat and cook for 5 minutes, your delicious vegan meat is ready to eat. Server hot!",
      life: "15 days",
    },
    images: [
      "https://i.postimg.cc/rm78k5s6/vegmeat-3.jpg",
      "https://i.postimg.cc/TwKRFtRq/vegmeat-4.jpg",
      "https://i.postimg.cc/Hsgg9Y7t/vegmeat-2.jpg",
      "https://i.postimg.cc/HxR18Mqp/vegmeat-1.jpg",
    ],
    ratings: 8000,
    reviews: 40,
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000020",
    type: "munchies",
    name: "Lay's Classic Chips",
    seller: "Lay's India",
    stars: 4.8,
    tag: ["snacks", "chips"],
    details: {
      stock: 20,
      price: 39,
      price2: 40,
      weight: "20g",
      packaging: "Plastic Packet",
      ingredients: "Potatoes, Salt, Sugar, Spices, Citric Acid",
      description:
        "Vegan's Special Chips is a pure vegan and extremely delicious chips. It's perfect for snacks. Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a dry place. Once opened, consume within 2 days. Do not freeze.",
      life: "120 days",
    },
    images: [
      "https://www.urbangroc.com/wp-content/uploads/2021/05/salted-chips-01.jpg",
      "https://m.media-amazon.com/images/I/71HofFavxML.jpg",
      "https://m.media-amazon.com/images/I/71uN3Nd43UL._AC_UF1000,1000_QL80_.jpg",
    ],
    ratings: 100,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000021"],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000021",
    type: "munchies",
    name: "Lay's Tomato Chips",
    seller: "Lay's India",
    stars: 4.8,
    tag: ["snacks", "chips"],
    details: {
      stock: 20,
      price: 39,
      price2: 40,
      weight: "20g",
      packaging: "Plastic Packet",
      ingredients: "Potatoes, Salt, Sugar, Spices, Citric Acid",
      description:
        "Vegan's Special Chips is a pure vegan and extremely delicious chips. It's perfect for snacks. Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a dry place. Once opened, consume within 2 days. Do not freeze.",
      life: "120 days",
    },
    images: [
      "https://m.media-amazon.com/images/I/71YgoSM0ioL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/71FMaRg8H2L._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/61gmZr2S-WL.jpg",
    ],
    ratings: 80,
    reviews: 15,
    rrlink: "https://vegancorner.vercel.app",
    related: ["00000020"],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000022",
    type: "munchies",
    name: "Lay's Onion Chips",
    seller: "Lay's India",
    tag: ["snacks", "chips"],
    details: {
      stock: 25,
      price: 39,
      price2: 40,
      quantity: "20g",
      packaging: "Plastic Packet",
      ingredients: "Potatoes, Salt, Sugar, Spices, Citric Acid",
      description:
        "Vegan's Special Lay's Chips is a pure vegan and extremely delicious chips.The cream used is based onn plant extracts. It's perfect for snacks. Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a dry place. Once opened, consume within 2 days. Do not freeze.",
      life: "120 days",
      _id: {
        $oid: "669a174b54ebc53e4ee6b72a",
      },
    },
    images: [
      "https://m.media-amazon.com/images/I/710dKk4a0cL.jpg",
      "https://i5.walmartimages.com/asr/4a22f777-af35-48b3-923e-8dc5ed4c1083.9a97c7544c2c96eaa2b331a00b41594f.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX6fyxmtf1VVGYSpuchnIj-lok3aoruj_0nw&s",
    ],
    rating: [4.1, 3.5, 4.7, 4.1, 3.9, 4.5, 4.8, 3, 4.6, 3.8, 3.75],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 1,
    sellingFrom: {
      $date: "2024-07-19T07:35:39.284Z",
    },
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000023",
    type: "grocery",
    name: "Vegan's Meat Premium",
    seller: "Vegan's Corner",
    tag: ["grocery", "meat"],
    details: {
      stock: 25,
      price: 449,
      price2: 549,
      quantity: "250g",
      packaging: "Plastic Packet",
      ingredients:
        "Vegetables, Soy extracts, Vinegar, Salt, Sugar, Spices, Citric Acid",
      description:
        "Veg Meat is a pure vegan and extremely delicious meat. It's perfect for dinner. Switch to Vegan's Corner Special Veg Meat .Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a fridge, or cool, dry place. Once opened, consume within 2 days. Do not freeze.Boil for 10 minutes, then prepare onion, spices and salt according to your taste for 10 minutes, add Vegan's Corner Veg Meat and cook for 5 minutes, your delicious vegan meat is ready to eat. Server hot!",
      life: "120 days",
      _id: {
        $oid: "669a5ddf183e4f8831ffc660",
      },
    },
    images: [
      "https://i.postimg.cc/3xwS74mz/vegmeat-5.jpg",
      "https://i.postimg.cc/zGPdfzkv/vegmeat-6.jpg",
      "https://i.postimg.cc/DzJxJ9Cg/vegmeat-7.jpg",
      "https://i.postimg.cc/J4x69cDb/vegmeat-8.jpg",
    ],
    ratings: [4.1, 3.5, 4.7, 4.1, 3.9, 4.5, 4.8, 3],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    sellingFrom: {
      $date: "2024-07-19T12:36:47.413Z",
    },
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000023",
    type: "grocery",
    name: "Vegan's Meat Premium",
    seller: "Vegan's Corner",
    tag: ["grocery", "meat"],
    details: {
      stock: 25,
      price: 449,
      price2: 549,
      quantity: "250g",
      packaging: "Plastic Packet",
      ingredients:
        "Vegetables, Soy extracts, Vinegar, Salt, Sugar, Spices, Citric Acid",
      description:
        "Veg Meat is a pure vegan and extremely delicious meat. It's perfect for dinner. Switch to Vegan's Corner Special Veg Meat .Enjoy Vegan Products for a healthy lifestyle",
      instructions:
        "Store in a fridge, or cool, dry place. Once opened, consume within 2 days. Do not freeze.Boil for 10 minutes, then prepare onion, spices and salt according to your taste for 10 minutes, add Vegan's Corner Veg Meat and cook for 5 minutes, your delicious vegan meat is ready to eat. Server hot!",
      life: "120 days",
      _id: {
        $oid: "669a5ddf183e4f8831ffc660",
      },
    },
    images: [
      "https://i.postimg.cc/3xwS74mz/vegmeat-5.jpg",
      "https://i.postimg.cc/zGPdfzkv/vegmeat-6.jpg",
      "https://i.postimg.cc/DzJxJ9Cg/vegmeat-7.jpg",
      "https://i.postimg.cc/J4x69cDb/vegmeat-8.jpg",
    ],
    ratings: [4.1, 3.5, 4.7, 4.1, 3.9, 4.5, 4.8, 3],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    sellingFrom: {
      $date: "2024-07-19T12:36:47.413Z",
    },
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000024",
    type: "grocery",
    name: "Vegan's Meat Deluxe",
    seller: "Vegan's Corner",
    tag: ["grocery", "meat"],
    details: {
      stock: 30,
      price: 499,
      price2: 599,
      quantity: "300g",
      packaging: "Eco-Friendly Box, Closed",
      ingredients:
        "Vegetables, Soy Protein, Natural Vinegar, Himalayan Salt, Organic Sugar, Mixed Spices, Citric Acid",
      description:
        "Vegan's Meat Deluxe is a plant-based meat alternative crafted for taste and health. Enjoy a delicious vegan meal with our premium-quality plant-based meat. Perfect for family dinners and healthy eating.",
      instructions:
        "Store in a refrigerator or a cool, dry place. Once opened, consume within 3 days. Do not freeze. Boil for 10 minutes, then sauté with onions, spices, and salt as per taste for 10 minutes. Add Vegan's Meat Deluxe and cook for 5 minutes. Serve hot!",
      life: "150 days",
    },
    images: [
      "https://i.postimg.cc/8PpwvxTR/vegmeat-12.jpg",
      "https://i.postimg.cc/90ppSYYw/vegmeat-10.jpg",
      "https://i.postimg.cc/MHx5dFV8/vegmeat-15.jpg",
    ],
    ratings: [4.3, 4.0, 4.6, 3.8, 4.2, 4.7, 3.5, 4.4],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },

  {
    id: "00000026",
    type: "grocery",
    name: "Vegan's Tikka Chunks",
    seller: "Vegan's Corner",
    tag: ["grocery", "vegan", "chunks"],
    details: {
      stock: 35,
      price: 429,
      price2: 529,
      quantity: "275g",
      packaging: "Vacuum-Sealed Pouch",
      ingredients:
        "Soy Protein, Chickpea Flour, Coconut Oil, Vinegar, Garlic, Ginger, Spices, Himalayan Salt",
      description:
        "Vegan's Tikka Chunks bring the authentic taste of Indian tikka to plant-based cuisine. Rich in flavor and texture, it's perfect for curries, wraps, or grilling.",
      instructions:
        "Store in a cool, dry place or refrigerate. Once opened, consume within 3 days. Pan-fry with oil for 8-10 minutes until golden brown or grill for 5 minutes. Serve hot with your favorite dips.",
      life: "100 days",
    },
    images: [
      "https://i.postimg.cc/BQmpBNvd/vegmeat-13.jpg",
      "https://i.postimg.cc/jjwM5NtB/vegmeat-17.jpg",
      "https://i.postimg.cc/s2kwZX2x/vegmeat-18.jpg",
    ],
    ratings: [4.6, 4.1, 4.3, 3.8, 4.5, 4.2, 3.9, 4.7],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },

  {
    id: "00000027",
    type: "quick foods",
    name: "Quick Tofu",
    seller: "Vegan's Corner",
    tag: ["grocery", "vegan", "tofu"],
    details: {
      stock: 50,
      price: 179,
      price2: 259,
      quantity: "300g",
      packaging: "Eco-Friendly Carton",
      ingredients:
        "Organic Soybeans, Filtered Water, Calcium Sulfate, Sea Salt",
      description:
        "Vegan's Organic Tofu is a soft yet firm, protein-rich alternative perfect for stir-fries, curries, and salads. Made from high-quality organic soybeans for a healthy and delicious meal.",
      instructions:
        "Refrigerate after opening. Consume within 5 days. Can be pan-fried, grilled, or added to soups and curries. For best texture, press tofu for 15 minutes before cooking.",
      life: "60 days",
    },
    images: [
      "https://i.postimg.cc/NF434Typ/quicktofu-10.jpg",
      "https://i.postimg.cc/1XrQj2d0/quicktofu-2.jpg",
      "https://i.postimg.cc/65zKLsnt/quicktofu-1.jpg",
    ],
    ratings: [3.7, 3.3, 4.5, 3.9, 4.6, 4.2, 4.1, 4.8],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 0,
    offer: false,
    others1: "",
    others2: [],
  },

  {
    id: "00000028",
    type: "quick foods",
    name: "Vegan's High-Protein Tofu",
    seller: "Vegan's Corner",
    tag: ["grocery", "quick foods", "tofu"],
    details: {
      stock: 42,
      price: 199,
      price2: 279,
      quantity: "350g",
      packaging: "Vacuum-Sealed Pack",
      ingredients:
        "Non-GMO Soybeans, Filtered Water, Calcium Sulfate, Sea Salt",
      description:
        "Vegan's High-Protein Tofu is a firm, nutrient-dense alternative, packed with plant-based protein. Ideal for grilling, stir-fries, or adding to protein-rich meals.",
      instructions:
        "Keep refrigerated. Use within 4 days after opening. For best texture, press tofu for 15 minutes before cooking. Suitable for frying, baking, or blending into sauces.",
      life: "75 days",
    },
    images: [
      "https://i.postimg.cc/d3wMrn0h/quicktofu-9.jpg",
      "https://i.postimg.cc/RVC50P88/quicktofu-12.jpg",
      "https://i.postimg.cc/13tQvWr6/quicktofu-4.jpg",
      "https://i.postimg.cc/HL8CgVKk/quicktofu-6.jpg",
    ],
    ratings: [4.4, 4.2, 3.8, 4.6, 4.7, 4.0, 4.1, 4.5],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },

  {
    id: "00000029",
    type: "quick foods",
    name: "Vegan's Silk Tofu",
    seller: "Vegan's Corner",
    tag: ["grocery", "quick foods", "tofu"],
    details: {
      stock: 45,
      price: 259,
      price2: 339,
      quantity: "280g",
      packaging: "Eco-Friendly Carton",
      ingredients: "Organic Soybeans, Filtered Water, Nigari, Sea Salt",
      description:
        "Vegan's Silk Tofu is a smooth, soft-textured tofu perfect for soups, smoothies, and creamy sauces. A nutritious and delicious addition to your plant-based diet.",
      instructions:
        "Keep refrigerated. Use within 5 days after opening. Best used in soups, desserts, or blended into creamy dishes. Not suitable for frying.",
      life: "90 days",
    },
    images: [
      "https://i.postimg.cc/XJwSrtnM/quicktofu-8.jpg",
      "https://i.postimg.cc/0Qg129Rd/quicktofu-7.jpg",
      "https://i.postimg.cc/7YqD2PCK/quicktofu-3.jpg",
      "https://i.postimg.cc/sgNRqpTL/quicktofu-5.jpg",
    ],
    ratings: [4.3, 4.5, 3.9, 4.7, 4.1, 4.0, 4.6, 4.2],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000030",
    type: "milk",
    name: "Premium Almond Milk",
    seller: "Vegan's Corner",
    tag: ["milk"],
    details: {
      stock: 60,
      price: 499,
      price2: 569,
      quantity: "1L",
      packaging: "Eco-Friendly Carton",
      ingredients:
        "Almonds, Filtered Water, Natural Sweetener, Sea Salt, Calcium, Vitamin D, Vitamin B12",
      description:
        "Vegan's Premium Almond Milk is a rich, creamy, and dairy-free alternative made from high-quality almonds. Perfect for coffee, smoothies, and cereals. Packed with essential vitamins and minerals for a healthy lifestyle.",
      instructions:
        "Refrigerate after opening. Consume within 5 days. Shake well before use. Suitable for drinking, cooking, and baking.",
      life: "90 days",
    },
    images: [
      "https://i.postimg.cc/y6Pt2mdT/almondmilk-1.jpg",
      "https://i.postimg.cc/y8wb0nQ7/almondmilk-4.jpg",
      "https://i.postimg.cc/5tLkgvTL/almondmilk-6.jpg",
    ],
    ratings: [4.5, 4.2, 4.6, 3.9, 4.3, 4.1, 4.7, 4.4],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000031",
    type: "milk",
    name: "Everyday Almond Milk",
    seller: "Vegan's Corner",
    tag: ["milk"],
    details: {
      stock: 80,
      price: 199,
      price2: 249,
      quantity: "1L",
      packaging: "Recyclable Tetra Pack",
      ingredients: "Almonds, Filtered Water, Natural Sweetener, Sea Salt",
      description:
        "Vegan's Everyday Almond Milk is a smooth and affordable dairy-free alternative made with simple, high-quality ingredients. Great for daily use in tea, coffee, cereals, and smoothies.",
      instructions:
        "Store in a cool, dry place. Refrigerate after opening and consume within 4 days. Shake well before use.",
      life: "60 days",
    },
    images: [
      "https://i.postimg.cc/63VgWRht/almondmilk-2.jpg",
      "https://i.postimg.cc/fTqFRMYt/almondmilk-9.jpg",
      "https://i.postimg.cc/L5H7nXyf/almondmilk-11.jpg",
      "https://i.postimg.cc/qvtFtWGm/almondmilk-5.jpg",
    ],
    ratings: [4.1, 3.8, 4.2, 3.9, 4.0, 3.7, 4.3, 4.1],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 0,
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000032",
    type: "milk",
    name: "Vegan's Family Almond Milk",
    seller: "Vegan's Corner",
    tag: ["milk", "value"],
    details: {
      stock: 100,
      price: 549,
      price2: 699,
      quantity: "3L (3 x 1L Packs)",
      packaging: "Bulk Recyclable Tetra Pack",
      ingredients:
        "Almonds, Filtered Water, Natural Sweetener, Sea Salt, Calcium",
      description:
        "Vegan's Family Pack Almond Milk is an affordable, large-pack option for households. Made with premium almonds and enriched with calcium, it’s ideal for daily consumption in tea, coffee, and smoothies.",
      instructions:
        "Store in a cool, dry place. Refrigerate after opening and consume within 4 days. Shake well before use. Best for families or bulk users.",
      life: "90 days",
    },
    images: [
      "https://i.postimg.cc/MHdLRS4L/almondmilk-3.jpg",
      "https://i.postimg.cc/gk2QpxLb/almondmilk-10.jpg",
      "https://i.postimg.cc/LXVQKSHs/almondmilk-8.jpg",
      "https://i.postimg.cc/TwxN41vS/almondmilk-7.jpg",
    ],
    ratings: [4.2, 4.5, 4.1, 3.9, 4.0, 4.4, 4.3, 4.6],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000033",
    type: "dairy",
    name: "Vegan's Plant-Based Cheese",
    seller: "Vegan's Corner",
    tag: ["cheese", "dairy"],
    details: {
      stock: 50,
      price: 299,
      price2: 479,
      quantity: "200g",
      packaging: "Resealable Eco-Friendly Pack",
      ingredients:
        "Cashews, Coconut Oil, Starch, Nutritional Yeast, Sea Salt, Natural Flavoring, Vegan Cultures",
      description:
        "Vegan's Plant-Based Cheese is a rich, creamy, and dairy-free alternative. Perfect for melting, spreading, or topping your favorite dishes. Made from high-quality plant-based ingredients for a delicious cheesy experience.",
      instructions:
        "Store in a refrigerator. Consume within 7 days after opening. Best for pizzas, sandwiches, or as a creamy spread.",
      life: "60 days",
    },
    images: [
      "https://i.postimg.cc/cHdTczQG/vegancheese-1.jpg",
      "https://i.postimg.cc/FKyD3vkx/vegancheese-4.jpg",
      "https://i.postimg.cc/2y6wsBcH/vegancheese-7.jpg",
      "https://i.postimg.cc/pdHB2Sc5/vegancheese-9.jpg",
    ],
    ratings: [4.4, 4.1, 4.3, 4.0, 3.9, 4.2, 4.5, 4.6, 5.0],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000034",
    type: "dairy",
    name: "Vegan's Everyday Cheese",
    seller: "Vegan's Corner",
    tag: [ "cheese", "dairy"],
    details: {
      stock: 75,
      price: 249,
      price2: 299,
      quantity: "180g",
      packaging: "Simple Resealable Pack",
      ingredients:
        "Coconut Oil, Starch, Nutritional Yeast, Sea Salt, Natural Flavoring",
      description:
        "Vegan's Everyday Cheese is a budget-friendly dairy-free alternative, offering a mild cheesy flavor that’s great for daily use. Ideal for sandwiches, snacks, and quick meals.",
      instructions:
        "Store in a refrigerator. Consume within 5 days after opening. Best for melting on toast, mixing in pasta, or as a light spread.",
      life: "45 days",
    },
    images: [
      "https://i.postimg.cc/5tdsXyy0/vegancheese-2.jpg",
      "https://i.postimg.cc/L4CvzN5G/vegancheese-5.jpg",
      "https://i.postimg.cc/kg8cPCsd/vegancheese-11.jpg",
    ],
    ratings: [4.0, 3.7, 4.1, 3.8, 3.9, 4.2, 4.0, 3.6],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 0,
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000035",
    type: "dairy",
    name: "Vegan's Classic Cheese",
    seller: "Vegan's Corner",
    tag: [ "cheese", "dairy"],
    details: {
      stock: 80,
      price: 269,
      price2: 319,
      quantity: "200g",
      packaging: "Simple Vacuum-Sealed Pack",
      ingredients:
        "Coconut Oil, Modified Starch, Nutritional Yeast, Sea Salt, Paprika Extract, Vegan Cultures",
      description:
        "Vegan's Classic Cheddar-Style Cheese is an affordable, dairy-free alternative with a mild, slightly tangy taste. Perfect for grilling, melting, and snacking. Enjoy the rich texture in burgers, sandwiches, or as a topping.",
      instructions:
        "Refrigerate after opening. Best used within 5 days. Ideal for melting, grating, or eating as is.",
      life: "50 days",
    },
    images: [
      "https://i.postimg.cc/SsVd1Gr2/vegancheese-3.jpg",
      "https://i.postimg.cc/4NYPwVhy/vegancheese-8.jpg",
      "https://i.postimg.cc/wMGVgTn9/vegancheese-6.jpg",
      "https://i.postimg.cc/fT1KPyxK/vegancheese-10.jpg",
    ],
    ratings: [4.1, 3.9, 4.0, 3.7, 4.2, 3.8, 4.3, 3.9],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 1,
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000036",
    type: "dairy",
    name: "Vegan's Plant-Based Curd",
    seller: "Vegan's Corner",
    tag: [ "curd", "dairy"],
    details: {
      stock: 100,
      price: 299,
      price2: 349,
      quantity: "400g",
      packaging: "Eco-Friendly Recyclable Tub",
      ingredients:
        "Coconut Milk, Cashew Paste, Tapioca Starch, Live Vegan Cultures, Sea Salt",
      description:
        "Vegan's Natural Plant-Based Curd is a rich and creamy dairy-free alternative. Perfect for smoothies, cooking, or enjoying as is. Made with high-quality plant-based ingredients for a probiotic-rich and gut-friendly experience.",
      instructions:
        "Store in a refrigerator. Consume within 5 days after opening. Best enjoyed chilled and can be used for making raita, buttermilk, or as a healthy dip.",
      life: "30 days",
    },
    images: [
      "https://i.postimg.cc/ydr9SpjP/vegancurd-1.jpg",
      "https://i.postimg.cc/NGz7yFPc/vegancurd-3.jpg",
      "https://i.postimg.cc/T1pV7v1F/vegancurd-4.jpg",
      "https://i.postimg.cc/8z8RH3SX/vegancurd-7.jpg",
    ],
    ratings: [4.3, 4.0, 4.2, 3.9, 4.1, 4.4, 4.5, 4.0],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },

  {
    id: "00000037",
    type: "dairy",
    name: "Vegan's Everyday Curd",
    seller: "Vegan's Corner",
    tag: [ "curd", "dairy"],
    details: {
      stock: 120,
      price: 149,
      price2: 199,
      quantity: "350g",
      packaging: "Simple Plastic Tub",
      ingredients: "Soy Milk, Tapioca Starch, Vegan Cultures, Sea Salt",
      description:
        "Vegan's Everyday Curd is a budget-friendly dairy-free curd with a light, tangy taste. Ideal for cooking, making buttermilk, or enjoying with meals. A cost-effective and nutritious choice for daily consumption.",
      instructions:
        "Refrigerate and consume within 4 days of opening. Best used in curries, raita, and smoothies.",
      life: "25 days",
    },
    images: [
      "https://i.postimg.cc/s2m53gZb/vegancurd-10.jpg",
      "https://i.postimg.cc/8c9hxXr5/vegancurd-5.jpg",
      "https://i.postimg.cc/kgxxhcMJ/vegancurd-8.jpg",
    ],
    ratings: [4.0, 3.8, 3.9, 4.1, 3.7, 4.0, 3.9, 3.8],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 0,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000038",
    type: "dairy",
    name: "Vegan's Premium Almond Curd",
    seller: "Vegan's Corner",
    tag: [ "curd", "dairy"],
    details: {
      stock: 80,
      price: 299,
      price2: 349,
      quantity: "450g",
      packaging: "Eco-Friendly Glass Jar",
      ingredients: "Almond Milk, Coconut Cream, Vegan Cultures, Himalayan Salt",
      description:
        "Vegan's Premium Almond Curd is a rich and creamy dairy-free alternative made from high-quality almond milk. Loaded with probiotics for gut health, it has a naturally nutty and smooth texture, perfect for direct consumption or cooking.",
      instructions:
        "Keep refrigerated. Best used within 6 days of opening. Ideal for smoothies, desserts, or as a dip.",
      life: "35 days",
    },
    images: [
      "https://i.postimg.cc/zf8nmg3n/vegancurd-9.jpg",
      "https://i.postimg.cc/LXyk389j/vegancurd-2.jpg",
      "https://i.postimg.cc/m213740F/vegancurd-6.jpg",
    ],
    ratings: [4.5, 4.3, 4.6, 4.4, 4.2, 4.5, 4.7, 4.3],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 2,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000039",
    type: "grocery",
    name: "Plant-Based Egg Mix",
    seller: "Vegan's Corner",
    tag: ["grocery", "egg"],
    details: {
      stock: 90,
      price: 349,
      price2: 399,
      quantity: "250g",
      packaging: "Resealable Pouch",
      ingredients:
        "Chickpea Flour, Tapioca Starch, Nutritional Yeast, Black Salt, Turmeric, Plant-Based Protein, Xanthan Gum",
      description:
        "Vegan's Plant-Based Egg Mix is the perfect egg substitute for scrambles, omelets, and baking. High in protein, rich in flavor, and easy to prepare—just mix with water and cook like a regular egg!",
      instructions:
        "Mix 2 tbsp of Vegan's Plant-Based Egg Mix with 4 tbsp of water. Stir well and cook on a pan for scrambles, omelets, or baking. Store in a cool, dry place.",
      life: "180 days",
    },
    images: [
      "https://i.postimg.cc/MHmMqWHv/veganegg-1.jpg",
      "https://i.postimg.cc/1tNDhhDq/veganegg-10.jpg",
      "https://i.postimg.cc/6qrRqrj6/veganegg-12.jpg",
      "https://i.postimg.cc/Wb7gP7qX/veganegg-2.jpg",
    ],
    ratings: [4.3, 4.0, 4.2, 3.9, 4.4, 4.5, 4.6, 4.3],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 0,
    offer: false,
    others1: "",
    others2: [],
  },
  {
    id: "00000040",
    type: "grocery",
    name: "Vegan's EVO Egg Powder",
    seller: "Vegan's Corner",
    tag: ["grocery", "egg"],
    details: {
      stock: 150,
      price: 209,
      price2: 349,
      quantity: "200g",
      packaging: "Simple Ziplock Pouch",
      ingredients:
        "Soy Flour, Corn Starch, Baking Soda, Kala Namak (Black Salt), Turmeric",
      description:
        "Vegan's Everyday Egg Powder is a cost-effective egg alternative for baking, pancakes, and scrambled eggs. Perfect for those on a budget without compromising taste or texture.",
      instructions:
        "Mix 1 tbsp of egg powder with 3 tbsp of water. Stir well and use in cooking or baking. Store in a cool, dry place.",
      life: "160 days",
    },
    images: [
      "https://i.postimg.cc/dQrG5FsM/veganegg-7.jpg",
      "https://i.postimg.cc/5tXCLd7R/veganegg-4.jpg",
      "https://i.postimg.cc/8Cch4r5w/veganegg-8.jpg",
      "https://i.postimg.cc/1XhwyCKY/veganegg-9.jpg",
    ],
    ratings: [4.0, 3.8, 3.9, 4.1, 3.7, 4.0, 3.8, 3.9],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 1,
    offer: true,
    others1: "",
    others2: [],
  },
  {
    id: "00000041",
    type: "grocery",
    name: "Vegan's Liquid Egg Substitute",
    seller: "Vegan's Corner",
    tag: ["grocery", "egg"],
    details: {
      stock: 80,
      price: 399,
      price2: 449,
      quantity: "500ml",
      packaging: "Eco-Friendly Bottle",
      ingredients:
        "Mung Bean Protein, Nutritional Yeast, Black Salt, Turmeric, Xanthan Gum, Water",
      description:
        "Vegan's Liquid Egg Substitute is a premium plant-based egg replacement that looks, cooks, and tastes like real eggs. Perfect for scrambles, omelets, and French toast.",
      instructions:
        "Shake well before use. Pour directly into a pan for scrambles or mix into batters for baking. Keep refrigerated and consume within 7 days after opening.",
      life: "45 days",
    },
    images: [
      "https://i.postimg.cc/zXNKMQvy/veganegg-6.jpg",
      "https://i.postimg.cc/Ss8Y1LpL/veganegg-3.jpg",
      "https://i.postimg.cc/430pSNHG/veganegg-11.jpg",
      "https://i.postimg.cc/1XQnkg9k/veganegg-5.jpg",
    ],
    ratings: [4.5, 4.3, 4.6, 4.4, 4.2, 4.5, 4.7, 4.3],
    reviews: [],
    rrlink: "https://vegancorner.vercel.app",
    related: [],
    priority: 1,
    offer: false,
    others1: "",
    others2: [],
  },
];
